# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x1a\x1bgoogle/protobuf/empty.proto\"l\n\x07Product\x12\x1a\n\x12product_identifier\x18\x01 \x01(\x05\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x18\n\x10product_quantity\x18\x03 \x01(\x05\x12\x15\n\rproduct_price\x18\x04 \x01(\x02\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t\"/\n\x11ProductIdentifier\x12\x1a\n\x12product_identifier\x18\x01 \x01(\x05\"@\n\x08Quantity\x12\x1a\n\x12product_identifier\x18\x01 \x01(\x05\x12\x18\n\x10product_quantity\x18\x02 \x01(\x05\x32\xf5\x01\n\x10InventoryService\x12\x1f\n\nAddProduct\x12\x08.Product\x1a\x07.Status\x12.\n\x0eGetProductById\x12\x12.ProductIdentifier\x1a\x08.Product\x12,\n\x15UpdateProductQuantity\x12\t.Quantity\x1a\x08.Product\x12,\n\rDeleteProduct\x12\x12.ProductIdentifier\x1a\x07.Status\x12\x34\n\x0eGetAllProducts\x12\x16.google.protobuf.Empty\x1a\x08.Product0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCT']._serialized_start=48
  _globals['_PRODUCT']._serialized_end=156
  _globals['_STATUS']._serialized_start=158
  _globals['_STATUS']._serialized_end=182
  _globals['_PRODUCTIDENTIFIER']._serialized_start=184
  _globals['_PRODUCTIDENTIFIER']._serialized_end=231
  _globals['_QUANTITY']._serialized_start=233
  _globals['_QUANTITY']._serialized_end=297
  _globals['_INVENTORYSERVICE']._serialized_start=300
  _globals['_INVENTORYSERVICE']._serialized_end=545
# @@protoc_insertion_point(module_scope)
